---
- name: Install WordPress with Nginx, PHP-FPM, and MariaDB on RHEL 9
  hosts: webservers
  become: true
  vars:
    wp_db_name: wordpress
    wp_db_user: wpuser
    wp_db_password: Tributary-Imprudent-Overdrawn6
    wp_root: /usr/share/nginx/html
    server_name: 165.22.59.114  # Ganti dengan domain/IP
    wp_admin_user: admin
    wp_admin_password: Ellipse-Props-Chop7
    wp_admin_email: admin@yopmail.com
    wp_site_title: "My WordPress Site"
    php_fpm_sock: /run/php-fpm/www.sock

  tasks:
    - name: Update cache paket dnf
      ansible.builtin.dnf:
        update_cache: yes

    - name: Instal paket yang dibutuhkan
      ansible.builtin.dnf:
        name:
          - nginx
          - mariadb-server
          - php
          - php-mysqlnd
          - php-fpm
          - php-json
          - php-gd
          - php-cli
          - php-zip
          - php-mbstring
          - unzip
          - policycoreutils-python-utils
        state: present

    - name: Aktifkan dan jalankan layanan
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - nginx
        - mariadb
        - php-fpm

    - name: Pastikan database WordPress ada (via socket auth)
      community.mysql.mysql_db:
        name: "{{ wp_db_name }}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Pastikan user WordPress ada (via socket auth)
      community.mysql.mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        host: "localhost"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        column_case_sensitive: false

    - name: Pastikan direktori web root ada
      ansible.builtin.file:
        path: "{{ wp_root }}"
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Cek apakah WordPress sudah terinstal
      ansible.builtin.stat:
        path: "{{ wp_root }}/wp-includes/version.php"
      register: wp_version_file

    - name: Validasi instalasi WordPress jika ada
      ansible.builtin.stat:
        path: "{{ wp_root }}/{{ item }}"
      register: wp_core_files
      loop:
        - wp-load.php
        - wp-settings.php
        - index.php
      when: wp_version_file.stat.exists

    - name: Tentukan apakah perlu install ulang WordPress
      ansible.builtin.set_fact:
        wp_needs_install: "{{ not wp_version_file.stat.exists or (wp_core_files.results | default([]) | selectattr('stat.exists', 'equalto', false) | list | length > 0) }}"

    - name: Unduh WordPress terbaru
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/latest.zip
        mode: '0644'
      when: wp_needs_install | bool

    - name: Kosongkan direktori sementara (jika ada)
      ansible.builtin.file:
        path: /tmp/wordpress_extract
        state: absent
      when: wp_needs_install | bool

    - name: Buat direktori sementara untuk ekstraksi
      ansible.builtin.file:
        path: /tmp/wordpress_extract
        state: directory
        mode: '0755'
      when: wp_needs_install | bool

    - name: Ekstrak WordPress ke direktori sementara
      ansible.builtin.unarchive:
        src: /tmp/latest.zip
        dest: /tmp/wordpress_extract
        remote_src: yes
        extra_opts: [ "-o" ]
      when: wp_needs_install | bool

    - name: Salin file WordPress ke direktori web root
      ansible.builtin.copy:
        src: /tmp/wordpress_extract/wordpress/
        dest: "{{ wp_root }}/"
        owner: nginx
        group: nginx
        mode: '0755'
        remote_src: yes
      when: wp_needs_install | bool

    - name: Bersihkan direktori sementara
      ansible.builtin.file:
        path: /tmp/wordpress_extract
        state: absent
      when: wp_needs_install | bool

    - name: Buat file konfigurasi PHP-FPM agar berjalan dengan Nginx
      ansible.builtin.lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^;?listen\.owner'
        line: 'listen.owner = nginx'

    - name: Pastikan PHP-FPM listen socket diset ke Unix socket
      ansible.builtin.lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen ='
        line: "listen = {{ php_fpm_sock }}"

    - name: Restart PHP-FPM agar perubahan diterapkan
      ansible.builtin.systemd:
        name: php-fpm
        state: restarted

    - name: Hapus konfigurasi default bawaan Nginx
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Buat konfigurasi Nginx untuk WordPress
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/wordpress.conf
        content: |
          server {
              listen       80;
              server_name  _;
              root         {{ wp_root }};
              index index.php index.html;

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include fastcgi_params;
                  fastcgi_pass unix:{{ php_fpm_sock }};
                  fastcgi_index index.php;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              }

              location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                  expires max;
                  log_not_found off;
              }
          }

    - name: Tes konfigurasi Nginx
      ansible.builtin.command:
        cmd: nginx -t
      register: nginx_test
      failed_when: "'successful' not in nginx_test.stderr"
      changed_when: false

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    - name: Set SELinux agar Nginx dapat mengakses file WordPress
      ansible.builtin.command:
        cmd: chcon -R -t httpd_sys_rw_content_t {{ wp_root }}
      changed_when: false

    - name: Cek apakah wp-config.php sudah ada
      ansible.builtin.stat:
        path: "{{ wp_root }}/wp-config.php"
      register: wp_config_file

    - name: Validasi wp-config.php jika ada
      ansible.builtin.shell:
        cmd: "grep -q \"define('DB_NAME'\" {{ wp_root }}/wp-config.php && grep -q \"AUTH_KEY\" {{ wp_root }}/wp-config.php"
      register: wp_config_valid
      failed_when: false
      changed_when: false
      when: wp_config_file.stat.exists

    - name: Fetch WordPress salt keys
      ansible.builtin.uri:
        url: https://api.wordpress.org/secret-key/1.1/salt/
        return_content: yes
      register: wp_salt_keys
      delegate_to: localhost
      become: false
      when: not wp_config_file.stat.exists or (wp_config_file.stat.exists and wp_config_valid.rc != 0)

    - name: Deploy wp-config.php dari template
      ansible.builtin.template:
        src: templates/wp-config.php.j2
        dest: "{{ wp_root }}/wp-config.php"
        owner: nginx
        group: nginx
        mode: '0644'
      when: not wp_config_file.stat.exists or (wp_config_file.stat.exists and wp_config_valid.rc != 0)

    - name: Install WP-CLI
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: '0755'

    - name: Verifikasi apakah WordPress sudah terinstal
      ansible.builtin.command:
        cmd: /usr/local/bin/wp core is-installed --path={{ wp_root }} --allow-root
      register: wp_installed
      failed_when: false
      changed_when: false

    - name: Install WordPress via WP-CLI
      ansible.builtin.command:
        cmd: >
          /usr/local/bin/wp core install
          --url=http://{{ server_name }}
          --title="{{ wp_site_title }}"
          --admin_user={{ wp_admin_user }}
          --admin_password={{ wp_admin_password }}
          --admin_email={{ wp_admin_email }}
          --path={{ wp_root }}
          --allow-root
      when: wp_installed.rc != 0

    - name: Set ownership dan permission final untuk WordPress
      ansible.builtin.file:
        path: "{{ wp_root }}"
        owner: nginx
        group: nginx
        recurse: yes
        state: directory

    - name: Install python3-firewall library (required by firewalld module)
      ansible.builtin.dnf:
        name: python3-firewall
        state: present

    # ---------------------------------------
    # Perbaikan firewalld
    # ---------------------------------------
    - name: Pastikan firewalld dan dependensinya terpasang
      ansible.builtin.dnf:
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: Pastikan firewalld aktif dan berjalan
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started

    - name: Tunggu sampai firewalld siap menerima perintah
      ansible.builtin.command: firewall-cmd --state
      register: fw_state
      retries: 5
      delay: 2
      until: fw_state.rc == 0
      changed_when: false


    - name: Open HTTP and HTTPS ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 80/tcp
        - 443/tcp
      become: true

  handlers:
    - name: reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
